# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-16 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=100)),
                ('ctime1', models.DateTimeField()),
                ('option2', models.CharField(max_length=100)),
                ('ctime2', models.DateTimeField()),
                ('option3', models.CharField(max_length=100)),
                ('ctime3', models.DateTimeField()),
                ('astate1', models.IntegerField(choices=[(0, '未审批'), (1, '拒绝'), (2, '通过')], default=0)),
                ('atime1', models.DateTimeField()),
                ('astate2', models.IntegerField(choices=[(0, '未审批'), (1, '拒绝'), (2, '通过')], default=0)),
                ('atime2', models.DateTimeField()),
                ('astate3', models.IntegerField(choices=[(0, '未审批'), (1, '拒绝'), (2, '通过')], default=0)),
                ('atime3', models.DateTimeField()),
                ('sinformation', models.CharField(max_length=100)),
                ('stime', models.DateField()),
                ('approval1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a1', to=settings.AUTH_USER_MODEL)),
                ('approval2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a2', to=settings.AUTH_USER_MODEL)),
                ('approval3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientnum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('addition', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractnum', models.AutoField(primary_key=True, serialize=False)),
                ('contractname', models.CharField(max_length=40)),
                ('begintime', models.DateField()),
                ('endtime', models.DateField()),
                ('content', models.CharField(max_length=200)),
                ('state', models.IntegerField(choices=[(0, '待分配'), (1, '会签中'), (2, '定稿中'), (3, '审批中'), (4, '签订中'), (5, '签订完成')], default=0)),
                ('file', models.FileField(upload_to='')),
                ('clientnum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_app.Client')),
                ('draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('fun1', models.BooleanField(default=False)),
                ('fun2', models.BooleanField(default=False)),
                ('fun3', models.BooleanField(default=False)),
                ('fun4', models.BooleanField(default=False)),
                ('fun5', models.BooleanField(default=False)),
                ('fun6', models.BooleanField(default=False)),
                ('fun7', models.BooleanField(default=False)),
                ('fun8', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='administration',
            name='contractnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Contract'),
        ),
        migrations.AddField(
            model_name='administration',
            name='countersign1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administration',
            name='countersign2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administration',
            name='countersign3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administration',
            name='sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_app.Role'),
        ),
    ]
