# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-16 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientnum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
