# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20181216_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
