# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-17 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20181216_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='fun8',
        ),
    ]
