# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-17 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_remove_role_fun8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
