# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_auto_20181218_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='fun7',
        ),
    ]
