# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0011_auto_20181219_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='contractnum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account_app.Contract'),
        ),
    ]
