# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-22 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_auto_20181219_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='option1',
            new_name='aoption1',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='option2',
            new_name='aoption2',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='option3',
            new_name='aoption3',
        ),
        migrations.AddField(
            model_name='administration',
            name='coption1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='administration',
            name='coption2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='administration',
            name='coption3',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
