# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-22 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0013_auto_20181222_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='aoption1',
            new_name='aopinion1',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='aoption2',
            new_name='aopinion2',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='aoption3',
            new_name='aopinion3',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='coption1',
            new_name='copinion1',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='coption2',
            new_name='copinion2',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='coption3',
            new_name='copinion3',
        ),
    ]
