# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-23 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0014_auto_20181222_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='aall',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='administration',
            name='ahas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administration',
            name='call',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='administration',
            name='chas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.IntegerField(choices=[(-1, '未通过'), (0, '待分配'), (1, '会签中'), (2, '定稿中'), (3, '审批中'), (4, '签订中'), (5, '签订完成')], default=0),
        ),
    ]
